import TechnologyTag from "../components/TechnologyTag.tsx";
import "/src/css/ProjectPage.css";
import MyTypewriter from "../components/MyTypewriter.tsx";
import { useNavigate } from "react-router";
import ScrollToTop from "../components/ScrollToTop.tsx";

function ChessEngineProject() {
    const navigate = useNavigate();

    return (
        <>
            <title>Chess Engine</title>
            <ScrollToTop />
            <div className="project">
                <div className="project-container">
                    {MyTypewriter("Chess Engine")}
                    <hr className={"divider"} />
                    <div className="image-container">
                        <img
                            className="project-image"
                            src={"/assets/chess_engine_imgs/chess-engine-example.png"}
                            alt={
                                "The chess engine running through Lichess playing against Stockfish"
                            }
                        ></img>
                        <div className="tech-list-div">
                            <p className="tech-list-text">Technologies used:</p>
                            <ul className="tech-list-list">
                                <TechnologyTag variant={"C++"} />
                            </ul>
                        </div>
                        <div className={"github-div"}>
                            <a
                                className={"github-button"}
                                target="_blank"
                                href="https://github.com/morgan-evans-24/Chess-Engine"
                            >
                                Go to GitHub page
                            </a>
                        </div>
                    </div>
                    <hr className={"divider"} />
                    <p>
                        I created a chess engine adhering to the Universal Chess Interface (UCI)
                        that was hosted on Lichess in C++.
                    </p>
                    <p>
                        The engine works primarily through the <i>Minimax algorithm</i>, as
                        described <a href={"connect4minimax"}>here</a>. The primary challenges
                        in developing a chess engine are the board representation and the optimisations which make
                        searching for moves more efficient, which are described below.
                    </p>
                    <hr className={"divider"} />
                    <h3>Board Representation</h3>
                    <p>
                        Board representation is a crucial issue when designing a chess engine. The correct
                        board representation can make move generation highly efficient. I have used a method known
                        as <i>bitboards</i> to represent the positions of different pieces. A bitboard is a
                        64-bit integer where each bit of the bitwise representation maps to a square on the board.
                        In this representation, a value of one in the bitboard shows a piece is present, and a zero
                        indicates that no piece is present. The limitation of bitboards is that they don't
                        show what type of piece takes up a space, only its position. This can be avoided by keeping
                        an array of bitboards, one for each type and colour of piece.
                    </p>
                    <div className="image-container">
                        <img
                            className="project-image"
                            src={"/assets/chess_engine_imgs/pawn-bitboard.png"}
                            alt={
                                "A grid of zeros and ones representing the starting position of the white pawns."
                            }
                        ></img>
                        <p className={"image-caption"}>
                            A bitboard representation of the starting squares for the white pawns.
                        </p>
                    </div>
                    <p>
                        The main advantage of representing the board in this manner is that bitboards utilise
                        very efficient bitwise operations such as shifts, logical 'and', and logical 'or'. For example,
                        a pawn single-advance can be generated by isolating each pawn in the bitboard, and then shifting that bit
                        left by eight.
                    </p>
                    <div className="image-container">
                        <img
                            className="project-image"
                            src={"/assets/chess_engine_imgs/bitboard-pawn-move.png"}
                            alt={
                                "A grid of zeros and ones representing the starting position of the white pawns. The " +
                                "pawn on the E file has moved forward by one square."
                            }
                        ></img>
                        <p className={"image-caption"}>
                            Shifting a pawns bit left by eight is equivalent to moving them forward on the board.
                        </p>
                    </div>
                    <hr className={"divider"} />
                    <h3>Alpha-Beta Pruning</h3>
                    <p>
                        <i>Alpha-Beta pruning</i> is a Minimax optimisation that aims to reduce the number of nodes in the
                        search tree. It still returns the same result as pure Minimax by only pruning nodes which do not
                        affect the final result.
                    </p>
                    <p>
                        It works by maintaining two values, alpha and beta. Alpha represents the minimum score the
                        maximising player has seen, whilst beta represents the maximum score the minimising player
                        has seen. If at any point, the score of a node exceeds beta, we can stop evaluating that route
                        further, as the minimising player would never let the game get to that point, assuming perfect
                        play.
                    </p>
                    <div className="image-container">
                        <img
                            className="project-image"
                            src={"/assets/chess_engine_imgs/alpha-beta-pruning.png"}
                            alt={
                                "A Minimax search tree with some of the branches pruned due to alpha-beta pruning."
                            }
                        ></img>
                        <p className={"image-caption"}>
                            The red dashes in this image represent pruning. The right-most pruned branch is never
                            explored because the maximising player won't choose that branch at the top level of the search.
                        </p>
                    </div>
                    <p>
                        Alpha-beta pruning is most effective when we evaluate the moves from best to worst. Following
                        this, to improve performance, the moves we evaluate at each node are assigned a cost heuristic.
                        This cost heuristic is determined by whether or not the move captures a piece,
                        promotes a pawn, or ends on a square attacked by an opponent's pawn.
                    </p>
                    <hr className={"divider"} />
                    <h3>Magic Bitboards</h3>
                    <p>
                        <i>Magic bitboards</i> are a technique used to speed up sliding piece move generation, the rook, bishop
                        and queen. Without magic bitboards, move generation is done using ray tracing. Using a rook
                        as an example, we would have to complete a loop for each of the four directions the rook can move
                        to find whether anything is blocking its path. This is very slow, and given that we have ten
                        sliding pieces on the board (four rooks, four bishops and two queens), speeding up this process
                        is a big timesaver.
                    </p>
                    <p>
                        The idea behind magic bitboards is to precompute the moves for every square of the board,
                        for every relevant blocker configuration, where a blocker is any other piece. This way, we
                        avoid having to loop over the movement directions of the sliding pieces. This way, accessing a
                        sliding piece's moves is simply a two-dimensional array lookup using the square the piece is on
                        and its blocker configuration. The main issue with this is that the blocker configuration is a
                        64-bit integer. This would mean our three 2D arrays would have to be 64-by-2^64 (1.18e+21 each!) to store all
                        possible configurations! For context, this is over twice as many array indexes as there are kilograms of
                        water in the Earth's oceans.
                    </p>
                    <div className="image-container">
                        <img
                            className="project-image"
                            src={"/assets/chess_engine_imgs/blockers.png"}
                            alt={
                                "A chess board with a white rook and black pawns acting as blockers."
                            }
                        ></img>
                        <p className={"image-caption"}>
                            The green arrows show the possible moves for the white rook. The black pawns are acting as
                            blockers here.
                        </p>
                    </div>
                    <p>
                        Fortunately, most of the bits in a blocker configuration are irrelevant for a given sliding piece.
                        Only the pieces in the way of the moving piece actually need to be considered as blockers,
                        dramatically reducing the possible number of configurations. This allows us to construct a much
                        smaller attack array for each square. The final challenge is efficiently mapping each blocker
                        configuration to a unique array index. Magic bitboards solve this problem by using a carefully
                        chosen 64-bit constant known as a <i>magic number</i>, to hash the blocker configuration
                        into an array index with no collisions.
                    </p>
                    <p>
                        So, in summary, we precompute a 2D array of possible moves for each sliding piece. We hash
                        the blocker configuration using a magic number, which we then use to index into the array along
                        with the starting square of the piece.
                    </p>
                    <hr className={"divider"} />
                    <h3>Transposition Table</h3>
                    <p>
                        <i>Transposition tables</i> are a method of storing the results of searching for a move for
                        later searches. The table relies on a concept called a transposition, which is that a single board
                        position can be reached from multiple paths.
                    </p>
                    <div className="image-container">
                        <img
                            className="project-image"
                            src={"/assets/chess_engine_imgs/transposition.png"}
                            alt={
                                "A graphic showcasing how the same board position can be reached in multiple ways."
                            }
                        ></img>
                        <p className={"image-caption"}>
                            The right two boards are transpositions of each other. Equal boards reached through different
                            paths.
                        </p>
                    </div>
                    <p>
                        During the move search after evaluating a Minimax node, the score and best move from that
                        position is stored in a map where the key is the Zobrist hash of the board at that node.
                        A Zobrist hash is a hash that is built by applying the XOR instruction across random numbers
                        given to each piece on the board, as well as whose turn it is, castling rights, and en-passant
                        squares. Now, whenever we see a board position where the Zobrist hash is already in our map,
                        we don't have to recompute the best move or score, and can instead just look at the values in the map.
                    </p>
                    <hr className={"divider"} />
                    <h3>Summary</h3>
                    <p>
                        Overall, I am very happy with how this project turned out. I managed to implement some advanced
                        techniques that definitely payed off in the performance of the engine. This was a very rewarding project,
                        and I am sure it has made me a better programmer.
                    </p>
                    <button
                        className="back-button"
                        onClick={() => {
                            navigate("/projects");
                        }}
                    >
                        Back to all projects
                    </button>
                </div>
            </div>
        </>
    );
}

export default ChessEngineProject;
